# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name=b'date added')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordsInSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_type', models.CharField(choices=[(b'1', b'reddit'), (b'0', b'twitter')], max_length=1)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link_to_content', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(verbose_name=b'date added')),
                ('keyword_in_social_media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.KeywordsInSocialMedia')),
            ],
        ),
    ]
