# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='keywordsinsocialmedia',
            old_name='keyword_id',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='searchresults',
            old_name='keyword_in_social_media_id',
            new_name='keyword_in_social_media',
        ),
    ]
