# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 00:17
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_keyword_last_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsinsocialmedia',
            name='social_media_type',
            field=django_mysql.models.EnumField(choices=[(b'twitter', b'twitter'), (b'reddit', b'reddit')]),
        ),
    ]
